name: CorApp Docker Series Build

on: [push]

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - uses:  actions/checkout@v4
      - name: docker login
        env:
            DOCKER_USER: ${{ secrets.DOCKER_USER }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run:  |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name:  docker build csharp
        run:  |
          docker build -t coreapp:debug -f Dockerfile .
      - name:  docker push
        run:  |
          docker tag coreapp:debug tastykibbles/coreapp:debug
          docker push tastykibbles/coreapp:debug
